/* Generated by Yosys 0.27+20 (git sha1 23826e515, x86_64-conda-linux-gnu-cc 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/root/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1679440662663/work=/usr/local/src/conda/yosys-0.27_21_g23826e515 -fdebug-prefix-map=/home/jacob/CFU-Playground/env/conda/envs/cfu-symbiflow=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

(* \amaranth.hierarchy  = "Cfu" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module Cfu(cmd_ready, cmd_payload_function_id, cmd_payload_inputs_0, cmd_payload_inputs_1, rsp_valid, rsp_ready, rsp_payload_outputs_0, reset, port0_addr, port1_addr, port2_addr, port3_addr, port0_din, port1_din, port2_din, port3_din, clk, rst, cmd_valid);
  reg \$auto$verilog_backend.cc:2097:dump_module$1  = 0;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$1 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$10 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal$11 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$12 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$13 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal$14 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$15 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$17 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal$18 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$19 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$2 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$21 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal$22 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$23 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$25 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal$26 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$27 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$29 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal$3 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$4 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$6 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal$7 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$8 ;
  (* src = "/home/jacob/CFU-Playground/third_party/python/amaranth/amaranth/hdl/ir.py:527" *)
  input clk;
  wire clk;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:185" *)
  input [9:0] cmd_payload_function_id;
  wire [9:0] cmd_payload_function_id;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:186" *)
  input [31:0] cmd_payload_inputs_0;
  wire [31:0] cmd_payload_inputs_0;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:187" *)
  input [31:0] cmd_payload_inputs_1;
  wire [31:0] cmd_payload_inputs_1;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:183" *)
  output cmd_ready;
  reg cmd_ready;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:182" *)
  input cmd_valid;
  wire cmd_valid;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:246" *)
  reg current_function_done;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:245" *)
  reg [2:0] current_function_id;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire fallback4_done;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] fallback4_in0;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] fallback4_in1;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] fallback4_output;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire fallback5_done;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] fallback5_in0;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] fallback5_in1;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] fallback5_output;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire fallback6_done;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] fallback6_in0;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] fallback6_in1;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] fallback6_output;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire fallback7_done;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] fallback7_in0;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] fallback7_in1;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] fallback7_output;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire fn0_done;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] fn0_in0;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] fn0_in1;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] fn0_output;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire fn1_done;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] fn1_in0;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] fn1_in1;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] fn1_output;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire fn2_done;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] fn2_in0;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] fn2_in1;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] fn2_output;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire fn3_done;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] fn3_in0;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] fn3_in1;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] fn3_output;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire fn3_start;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
  reg [1:0] fsm_state = 2'h0;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
  reg [1:0] \fsm_state$next ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:238" *)
  wire [2:0] funct3;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:239" *)
  wire [6:0] funct7;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] \funct7$30 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] \funct7$31 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] \funct7$32 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] \funct7$33 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] \funct7$34 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] \funct7$35 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] \funct7$36 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] \funct7$37 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:192" *)
  input [31:0] port0_addr;
  wire [31:0] port0_addr;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:193" *)
  input [31:0] port0_din;
  wire [31:0] port0_din;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:192" *)
  input [31:0] port1_addr;
  wire [31:0] port1_addr;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:193" *)
  input [31:0] port1_din;
  wire [31:0] port1_din;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:192" *)
  input [31:0] port2_addr;
  wire [31:0] port2_addr;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:193" *)
  input [31:0] port2_din;
  wire [31:0] port2_din;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:192" *)
  input [31:0] port3_addr;
  wire [31:0] port3_addr;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:193" *)
  input [31:0] port3_din;
  wire [31:0] port3_din;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:191" *)
  input reset;
  wire reset;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:190" *)
  output [31:0] rsp_payload_outputs_0;
  reg [31:0] rsp_payload_outputs_0;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:189" *)
  input rsp_ready;
  wire rsp_ready;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:188" *)
  output rsp_valid;
  reg rsp_valid;
  (* src = "/home/jacob/CFU-Playground/third_party/python/amaranth/amaranth/hdl/ir.py:527" *)
  output rst;
  wire rst;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire start;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire \start$16 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire \start$20 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire \start$24 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire \start$28 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire \start$5 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire \start$9 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:244" *)
  reg [2:0] stored_function_id = 3'h0;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:244" *)
  reg [2:0] \stored_function_id$next ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:247" *)
  reg [31:0] stored_output = 32'd0;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:247" *)
  reg [31:0] \stored_output$next ;
  always @(posedge clk)
    stored_function_id <= \stored_function_id$next ;
  always @(posedge clk)
    fsm_state <= \fsm_state$next ;
  always @(posedge clk)
    stored_output <= \stored_output$next ;
  fallback4 fallback4 (
    .done(fallback4_done),
    .in0(fallback4_in0),
    .in1(fallback4_in1),
    .\output (fallback4_output)
  );
  fallback5 fallback5 (
    .done(fallback5_done),
    .in0(fallback5_in0),
    .in1(fallback5_in1),
    .\output (fallback5_output)
  );
  fallback6 fallback6 (
    .done(fallback6_done),
    .in0(fallback6_in0),
    .in1(fallback6_in1),
    .\output (fallback6_output)
  );
  fallback7 fallback7 (
    .done(fallback7_done),
    .in0(fallback7_in0),
    .in1(fallback7_in1),
    .\output (fallback7_output)
  );
  fn0 fn0 (
    .done(fn0_done),
    .in0(fn0_in0),
    .in1(fn0_in1),
    .\output (fn0_output)
  );
  fn1 fn1 (
    .done(fn1_done),
    .in0(fn1_in0),
    .in1(fn1_in1),
    .\output (fn1_output)
  );
  fn2 fn2 (
    .done(fn2_done),
    .in0(fn2_in0),
    .in1(fn2_in1),
    .\output (fn2_output)
  );
  fn3 fn3 (
    .clk(clk),
    .done(fn3_done),
    .in0(fn3_in0),
    .in1(fn3_in1),
    .\output (fn3_output),
    .rst(rst),
    .start(fn3_start)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$1 ) begin end
    current_function_id = 3'h0;
    (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          current_function_id = funct3;
      /* \amaranth.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:284" */
      2'h2:
          current_function_id = stored_function_id;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$1 ) begin end
    current_function_done = 1'h0;
    (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          (* full_case = 32'd1 *)
          (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:277" *)
          casez (current_function_id)
            3'h0:
                current_function_done = \$signal$1 ;
            3'h1:
                current_function_done = \$signal$4 ;
            3'h2:
                current_function_done = \$signal$8 ;
            3'h3:
                current_function_done = \$signal$12 ;
            3'h4:
                current_function_done = \$signal$15 ;
            3'h5:
                current_function_done = \$signal$19 ;
            3'h6:
                current_function_done = \$signal$23 ;
            3'h?:
                current_function_done = \$signal$27 ;
          endcase
      /* \amaranth.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:284" */
      2'h2:
          (* full_case = 32'd1 *)
          (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:289" *)
          casez (current_function_id)
            3'h0:
                current_function_done = \$signal$1 ;
            3'h1:
                current_function_done = \$signal$4 ;
            3'h2:
                current_function_done = \$signal$8 ;
            3'h3:
                current_function_done = \$signal$12 ;
            3'h4:
                current_function_done = \$signal$15 ;
            3'h5:
                current_function_done = \$signal$19 ;
            3'h6:
                current_function_done = \$signal$23 ;
            3'h?:
                current_function_done = \$signal$27 ;
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$1 ) begin end
    cmd_ready = 1'h0;
    (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          cmd_ready = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$1 ) begin end
    \stored_function_id$next  = stored_function_id;
    (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:279" *)
          casez (cmd_valid)
            /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:279" */
            1'h1:
                \stored_function_id$next  = cmd_payload_function_id[2:0];
          endcase
    endcase
    (* src = "/home/jacob/CFU-Playground/third_party/python/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \stored_function_id$next  = 3'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$1 ) begin end
    \$signal$2  = 1'h0;
    \$signal$6  = 1'h0;
    \$signal$10  = 1'h0;
    \$signal$13  = 1'h0;
    \$signal$17  = 1'h0;
    \$signal$21  = 1'h0;
    \$signal$25  = 1'h0;
    \$signal$29  = 1'h0;
    (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:279" *)
          casez (cmd_valid)
            /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:279" */
            1'h1:
                (* full_case = 32'd1 *)
                (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:282" *)
                casez (current_function_id)
                  3'h0:
                      \$signal$2  = 1'h1;
                  3'h1:
                      \$signal$6  = 1'h1;
                  3'h2:
                      \$signal$10  = 1'h1;
                  3'h3:
                      \$signal$13  = 1'h1;
                  3'h4:
                      \$signal$17  = 1'h1;
                  3'h5:
                      \$signal$21  = 1'h1;
                  3'h6:
                      \$signal$25  = 1'h1;
                  3'h?:
                      \$signal$29  = 1'h1;
                endcase
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$1 ) begin end
    rsp_valid = 1'h0;
    (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:279" *)
          casez (cmd_valid)
            /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:279" */
            1'h1:
                (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
                casez (current_function_done)
                  /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:259" */
                  1'h1:
                      rsp_valid = 1'h1;
                endcase
          endcase
      /* \amaranth.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:284" */
      2'h2:
          (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
          casez (current_function_done)
            /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:259" */
            1'h1:
                rsp_valid = 1'h1;
          endcase
      /* \amaranth.decoding  = "WAIT_TRANSFER/1" */
      /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:291" */
      2'h1:
          rsp_valid = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$1 ) begin end
    rsp_payload_outputs_0 = 32'd0;
    (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:279" *)
          casez (cmd_valid)
            /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:279" */
            1'h1:
                (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
                casez (current_function_done)
                  /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:259" */
                  1'h1:
                      (* full_case = 32'd1 *)
                      (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:262" *)
                      casez (current_function_id)
                        3'h0:
                            rsp_payload_outputs_0 = \$signal ;
                        3'h1:
                            rsp_payload_outputs_0 = \$signal$3 ;
                        3'h2:
                            rsp_payload_outputs_0 = \$signal$7 ;
                        3'h3:
                            rsp_payload_outputs_0 = \$signal$11 ;
                        3'h4:
                            rsp_payload_outputs_0 = \$signal$14 ;
                        3'h5:
                            rsp_payload_outputs_0 = \$signal$18 ;
                        3'h6:
                            rsp_payload_outputs_0 = \$signal$22 ;
                        3'h?:
                            rsp_payload_outputs_0 = \$signal$26 ;
                      endcase
                endcase
          endcase
      /* \amaranth.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:284" */
      2'h2:
          (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
          casez (current_function_done)
            /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:259" */
            1'h1:
                (* full_case = 32'd1 *)
                (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:262" *)
                casez (current_function_id)
                  3'h0:
                      rsp_payload_outputs_0 = \$signal ;
                  3'h1:
                      rsp_payload_outputs_0 = \$signal$3 ;
                  3'h2:
                      rsp_payload_outputs_0 = \$signal$7 ;
                  3'h3:
                      rsp_payload_outputs_0 = \$signal$11 ;
                  3'h4:
                      rsp_payload_outputs_0 = \$signal$14 ;
                  3'h5:
                      rsp_payload_outputs_0 = \$signal$18 ;
                  3'h6:
                      rsp_payload_outputs_0 = \$signal$22 ;
                  3'h?:
                      rsp_payload_outputs_0 = \$signal$26 ;
                endcase
          endcase
      /* \amaranth.decoding  = "WAIT_TRANSFER/1" */
      /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:291" */
      2'h1:
          rsp_payload_outputs_0 = stored_output;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$1 ) begin end
    \fsm_state$next  = fsm_state;
    (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:279" *)
          casez (cmd_valid)
            /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:279" */
            1'h1:
                (* full_case = 32'd1 *)
                (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
                casez (current_function_done)
                  /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:259" */
                  1'h1:
                      (* full_case = 32'd1 *)
                      (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:263" *)
                      casez (rsp_ready)
                        /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:263" */
                        1'h1:
                            \fsm_state$next  = 2'h0;
                        /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:265" */
                        default:
                            \fsm_state$next  = 2'h1;
                      endcase
                  /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:269" */
                  default:
                      \fsm_state$next  = 2'h2;
                endcase
          endcase
      /* \amaranth.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:284" */
      2'h2:
          (* full_case = 32'd1 *)
          (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
          casez (current_function_done)
            /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:259" */
            1'h1:
                (* full_case = 32'd1 *)
                (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:263" *)
                casez (rsp_ready)
                  /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:263" */
                  1'h1:
                      \fsm_state$next  = 2'h0;
                  /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:265" */
                  default:
                      \fsm_state$next  = 2'h1;
                endcase
            /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:269" */
            default:
                \fsm_state$next  = 2'h2;
          endcase
      /* \amaranth.decoding  = "WAIT_TRANSFER/1" */
      /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:291" */
      2'h1:
          (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:296" *)
          casez (rsp_ready)
            /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:296" */
            1'h1:
                \fsm_state$next  = 2'h0;
          endcase
    endcase
    (* src = "/home/jacob/CFU-Playground/third_party/python/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \fsm_state$next  = 2'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$1 ) begin end
    \stored_output$next  = stored_output;
    (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:279" *)
          casez (cmd_valid)
            /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:279" */
            1'h1:
                (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
                casez (current_function_done)
                  /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:259" */
                  1'h1:
                      (* full_case = 32'd1 *)
                      (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:263" *)
                      casez (rsp_ready)
                        /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:263" */
                        1'h1:
                            /* empty */;
                        /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:265" */
                        default:
                            (* full_case = 32'd1 *)
                            (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:267" *)
                            casez (current_function_id)
                              3'h0:
                                  \stored_output$next  = \$signal ;
                              3'h1:
                                  \stored_output$next  = \$signal$3 ;
                              3'h2:
                                  \stored_output$next  = \$signal$7 ;
                              3'h3:
                                  \stored_output$next  = \$signal$11 ;
                              3'h4:
                                  \stored_output$next  = \$signal$14 ;
                              3'h5:
                                  \stored_output$next  = \$signal$18 ;
                              3'h6:
                                  \stored_output$next  = \$signal$22 ;
                              3'h?:
                                  \stored_output$next  = \$signal$26 ;
                            endcase
                      endcase
                endcase
          endcase
      /* \amaranth.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:284" */
      2'h2:
          (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
          casez (current_function_done)
            /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:259" */
            1'h1:
                (* full_case = 32'd1 *)
                (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:263" *)
                casez (rsp_ready)
                  /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:263" */
                  1'h1:
                      /* empty */;
                  /* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:265" */
                  default:
                      (* full_case = 32'd1 *)
                      (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:267" *)
                      casez (current_function_id)
                        3'h0:
                            \stored_output$next  = \$signal ;
                        3'h1:
                            \stored_output$next  = \$signal$3 ;
                        3'h2:
                            \stored_output$next  = \$signal$7 ;
                        3'h3:
                            \stored_output$next  = \$signal$11 ;
                        3'h4:
                            \stored_output$next  = \$signal$14 ;
                        3'h5:
                            \stored_output$next  = \$signal$18 ;
                        3'h6:
                            \stored_output$next  = \$signal$22 ;
                        3'h?:
                            \stored_output$next  = \$signal$26 ;
                      endcase
                endcase
          endcase
    endcase
    (* src = "/home/jacob/CFU-Playground/third_party/python/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \stored_output$next  = 32'd0;
    endcase
  end
  assign rst = reset;
  assign \funct7$37  = funct7;
  assign fallback7_in1 = cmd_payload_inputs_1;
  assign fallback7_in0 = cmd_payload_inputs_0;
  assign \funct7$36  = funct7;
  assign fallback6_in1 = cmd_payload_inputs_1;
  assign fallback6_in0 = cmd_payload_inputs_0;
  assign \funct7$35  = funct7;
  assign fallback5_in1 = cmd_payload_inputs_1;
  assign fallback5_in0 = cmd_payload_inputs_0;
  assign \funct7$34  = funct7;
  assign fallback4_in1 = cmd_payload_inputs_1;
  assign fallback4_in0 = cmd_payload_inputs_0;
  assign \funct7$33  = funct7;
  assign fn3_in1 = cmd_payload_inputs_1;
  assign fn3_in0 = cmd_payload_inputs_0;
  assign \funct7$32  = funct7;
  assign fn2_in1 = cmd_payload_inputs_1;
  assign fn2_in0 = cmd_payload_inputs_0;
  assign \funct7$31  = funct7;
  assign fn1_in1 = cmd_payload_inputs_1;
  assign fn1_in0 = cmd_payload_inputs_0;
  assign \funct7$30  = funct7;
  assign fn0_in1 = cmd_payload_inputs_1;
  assign fn0_in0 = cmd_payload_inputs_0;
  assign \start$28  = \$signal$29 ;
  assign \$signal$27  = fallback7_done;
  assign \$signal$26  = fallback7_output;
  assign \start$24  = \$signal$25 ;
  assign \$signal$23  = fallback6_done;
  assign \$signal$22  = fallback6_output;
  assign \start$20  = \$signal$21 ;
  assign \$signal$19  = fallback5_done;
  assign \$signal$18  = fallback5_output;
  assign \start$16  = \$signal$17 ;
  assign \$signal$15  = fallback4_done;
  assign \$signal$14  = fallback4_output;
  assign fn3_start = \$signal$13 ;
  assign \$signal$12  = fn3_done;
  assign \$signal$11  = fn3_output;
  assign \start$9  = \$signal$10 ;
  assign \$signal$8  = fn2_done;
  assign \$signal$7  = fn2_output;
  assign \start$5  = \$signal$6 ;
  assign \$signal$4  = fn1_done;
  assign \$signal$3  = fn1_output;
  assign start = \$signal$2 ;
  assign \$signal$1  = fn0_done;
  assign \$signal  = fn0_output;
  assign funct7 = cmd_payload_function_id[9:3];
  assign funct3 = cmd_payload_function_id[2:0];
endmodule

(* \amaranth.hierarchy  = "Cfu.fallback4" *)
(* generator = "Amaranth" *)
module fallback4(done, in0, in1, \output );
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  wire done;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  wire [31:0] \output ;
  assign in1s = in1;
  assign in0s = in0;
  assign done = 1'h1;
  assign \output  = in0;
endmodule

(* \amaranth.hierarchy  = "Cfu.fallback5" *)
(* generator = "Amaranth" *)
module fallback5(done, in0, in1, \output );
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  wire done;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  wire [31:0] \output ;
  assign in1s = in1;
  assign in0s = in0;
  assign done = 1'h1;
  assign \output  = in0;
endmodule

(* \amaranth.hierarchy  = "Cfu.fallback6" *)
(* generator = "Amaranth" *)
module fallback6(done, in0, in1, \output );
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  wire done;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  wire [31:0] \output ;
  assign in1s = in1;
  assign in0s = in0;
  assign done = 1'h1;
  assign \output  = in0;
endmodule

(* \amaranth.hierarchy  = "Cfu.fallback7" *)
(* generator = "Amaranth" *)
module fallback7(done, in0, in1, \output );
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  wire done;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  wire [31:0] \output ;
  assign in1s = in1;
  assign in0s = in0;
  assign done = 1'h1;
  assign \output  = in0;
endmodule

(* \amaranth.hierarchy  = "Cfu.fn0" *)
(* generator = "Amaranth" *)
module fn0(done, in0, in1, \output );
  (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:99" *)
  wire [31:0] \$1 ;
  (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:98" *)
  wire [12:0] \$10 ;
  (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:98" *)
  wire [13:0] \$12 ;
  (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:99" *)
  wire [14:0] \$14 ;
  (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:98" *)
  wire [8:0] \$2 ;
  (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:98" *)
  wire [9:0] \$4 ;
  (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:98" *)
  wire [10:0] \$6 ;
  (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:98" *)
  wire [11:0] \$8 ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  wire done;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  wire [31:0] \output ;
  assign \$10  = \$8  + (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:98" *) in1[15:8];
  assign \$12  = \$10  + (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:98" *) in1[23:16];
  assign \$14  = \$12  + (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:99" *) in1[31:24];
  assign \$1  = + (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:99" *) \$14 ;
  assign \$2  = in0[7:0] + (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:98" *) in0[15:8];
  assign \$4  = \$2  + (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:98" *) in0[23:16];
  assign \$6  = \$4  + (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:98" *) in0[31:24];
  assign \$8  = \$6  + (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:98" *) in1[7:0];
  assign in1s = in1;
  assign in0s = in0;
  assign done = 1'h1;
  assign \output  = \$1 ;
endmodule

(* \amaranth.hierarchy  = "Cfu.fn1" *)
(* generator = "Amaranth" *)
module fn1(done, in0, in1, \output );
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  wire done;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  wire [31:0] \output ;
  assign in1s = in1;
  assign in0s = in0;
  assign done = 1'h1;
  assign \output [7:0] = in0[31:24];
  assign \output [15:8] = in0[23:16];
  assign \output [23:16] = in0[15:8];
  assign \output [31:24] = in0[7:0];
endmodule

(* \amaranth.hierarchy  = "Cfu.fn2" *)
(* generator = "Amaranth" *)
module fn2(done, in0, in1, \output );
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  wire done;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  wire [31:0] \output ;
  assign in1s = in1;
  assign in0s = in0;
  assign done = 1'h1;
  assign \output [0] = in0[31];
  assign \output [1] = in0[30];
  assign \output [2] = in0[29];
  assign \output [3] = in0[28];
  assign \output [4] = in0[27];
  assign \output [5] = in0[26];
  assign \output [6] = in0[25];
  assign \output [7] = in0[24];
  assign \output [8] = in0[23];
  assign \output [9] = in0[22];
  assign \output [10] = in0[21];
  assign \output [11] = in0[20];
  assign \output [12] = in0[19];
  assign \output [13] = in0[18];
  assign \output [14] = in0[17];
  assign \output [15] = in0[16];
  assign \output [16] = in0[15];
  assign \output [17] = in0[14];
  assign \output [18] = in0[13];
  assign \output [19] = in0[12];
  assign \output [20] = in0[11];
  assign \output [21] = in0[10];
  assign \output [22] = in0[9];
  assign \output [23] = in0[8];
  assign \output [24] = in0[7];
  assign \output [25] = in0[6];
  assign \output [26] = in0[5];
  assign \output [27] = in0[4];
  assign \output [28] = in0[3];
  assign \output [29] = in0[2];
  assign \output [30] = in0[1];
  assign \output [31] = in0[0];
endmodule

(* \amaranth.hierarchy  = "Cfu.fn3" *)
(* generator = "Amaranth" *)
module fn3(done, start, in0, in1, rst, clk, \output );
  reg \$auto$verilog_backend.cc:2097:dump_module$2  = 0;
  (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:48" *)
  wire [32:0] \$1 ;
  (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:50" *)
  wire \$10 ;
  (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:38" *)
  wire \$12 ;
  (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:46" *)
  wire [32:0] \$14 ;
  (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:46" *)
  wire [32:0] \$15 ;
  (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:48" *)
  wire [32:0] \$2 ;
  (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:38" *)
  wire \$4 ;
  (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:50" *)
  wire \$6 ;
  (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:38" *)
  wire \$8 ;
  (* src = "/home/jacob/CFU-Playground/third_party/python/amaranth/amaranth/hdl/ir.py:527" *)
  input clk;
  wire clk;
  (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:30" *)
  reg [31:0] count = 32'd0;
  (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:30" *)
  reg [31:0] \count$next ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  reg done;
  (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:31" *)
  reg fsm_state = 1'h0;
  (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:31" *)
  reg \fsm_state$next ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  wire [31:0] \output ;
  (* src = "/home/jacob/CFU-Playground/third_party/python/amaranth/amaranth/hdl/ir.py:527" *)
  input rst;
  wire rst;
  (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:28" *)
  reg [31:0] s1 = 32'd0;
  (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:28" *)
  reg [31:0] \s1$next ;
  (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:29" *)
  reg [31:0] s2 = 32'd0;
  (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:29" *)
  reg [31:0] \s2$next ;
  (* src = "/home/jacob/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  input start;
  wire start;
  assign \$10  = ! (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:50" *) count;
  assign \$12  = in0 > (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:38" *) 6'h2e;
  assign \$15  = count - (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:46" *) 1'h1;
  always @(posedge clk)
    s1 <= \s1$next ;
  always @(posedge clk)
    s2 <= \s2$next ;
  always @(posedge clk)
    fsm_state <= \fsm_state$next ;
  always @(posedge clk)
    count <= \count$next ;
  assign \$2  = s1 + (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:48" *) s2;
  assign \$4  = in0 > (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:38" *) 6'h2e;
  assign \$6  = ! (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:50" *) count;
  assign \$8  = in0 > (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:38" *) 6'h2e;
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$2 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:31" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT/0" */
      /* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:32" */
      1'h0:
          \s1$next  = 32'd0;
      /* \amaranth.decoding  = "RUN/1" */
      /* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:44" */
      1'h1:
          \s1$next  = s2;
    endcase
    (* src = "/home/jacob/CFU-Playground/third_party/python/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \s1$next  = 32'd0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$2 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:31" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT/0" */
      /* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:32" */
      1'h0:
          \s2$next  = 32'd1;
      /* \amaranth.decoding  = "RUN/1" */
      /* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:44" */
      1'h1:
          \s2$next  = \$2 [31:0];
    endcase
    (* src = "/home/jacob/CFU-Playground/third_party/python/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \s2$next  = 32'd0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$2 ) begin end
    done = 1'h0;
    (* full_case = 32'd1 *)
    (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:31" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT/0" */
      /* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:32" */
      1'h0:
          (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:37" *)
          casez (start)
            /* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:37" */
            1'h1:
                (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:38" *)
                casez (\$4 )
                  /* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:38" */
                  1'h1:
                      done = 1'h1;
                endcase
          endcase
      /* \amaranth.decoding  = "RUN/1" */
      /* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:44" */
      1'h1:
          (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:50" *)
          casez (\$6 )
            /* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:50" */
            1'h1:
                done = 1'h1;
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$2 ) begin end
    \fsm_state$next  = fsm_state;
    (* full_case = 32'd1 *)
    (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:31" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT/0" */
      /* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:32" */
      1'h0:
          (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:37" *)
          casez (start)
            /* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:37" */
            1'h1:
                (* full_case = 32'd1 *)
                (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:38" *)
                casez (\$8 )
                  /* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:38" */
                  1'h1:
                      /* empty */;
                  /* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:41" */
                  default:
                      \fsm_state$next  = 1'h1;
                endcase
          endcase
      /* \amaranth.decoding  = "RUN/1" */
      /* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:44" */
      1'h1:
          (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:50" *)
          casez (\$10 )
            /* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:50" */
            1'h1:
                \fsm_state$next  = 1'h0;
          endcase
    endcase
    (* src = "/home/jacob/CFU-Playground/third_party/python/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \fsm_state$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$2 ) begin end
    \count$next  = count;
    (* full_case = 32'd1 *)
    (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:31" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT/0" */
      /* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:32" */
      1'h0:
          (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:37" *)
          casez (start)
            /* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:37" */
            1'h1:
                (* full_case = 32'd1 *)
                (* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:38" *)
                casez (\$12 )
                  /* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:38" */
                  1'h1:
                      /* empty */;
                  /* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:41" */
                  default:
                      \count$next  = in0;
                endcase
          endcase
      /* \amaranth.decoding  = "RUN/1" */
      /* src = "/home/jacob/CFU-Playground/proj/example_cfu_thesis/cfu.py:44" */
      1'h1:
          \count$next  = \$15 [31:0];
    endcase
    (* src = "/home/jacob/CFU-Playground/third_party/python/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \count$next  = 32'd0;
    endcase
  end
  assign \$1  = \$2 ;
  assign \$14  = \$15 ;
  assign in1s = in1;
  assign in0s = in0;
  assign \output  = s1;
endmodule
